# Generated by Django 5.1.3 on 2024-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_pad", "0003_node_city_node_country_node_email_node_house_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="node",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="retail_pad.node"
            ),
        ),
    ]
