# Generated by Django 5.1.3 on 2024-12-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_pad", "0004_node_network_lvl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="retail_pad.node",
            ),
        ),
    ]
