# Generated by Django 5.1.3 on 2024-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_pad", "0005_alter_product_node"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="node",
            options={
                "verbose_name": "Звено цепи",
                "verbose_name_plural": "Звенья цепи",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="node",
            name="network_lvl",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="уровень"
            ),
        ),
    ]
